##Linear Regression using TensorFlow

In this session, we will have a look at creating a linear regression model using tensorflow 2.0. Note that we already know the basics of linear regression and understand the implementation through sklearn. We will try to figure out how to do it using tensorflow tools that we have learnt.   


<i>Note that to keep this exercise simple and focused on tensorflow and its relevant functions, we will make a very simple model with very basic preprocessing.</i> 

#### Let us start with mounting our drive to be able to use the dataset stored in our dataset.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#### Let us install the latest version of tensorflow.


In [ ]:
!pip install tensorflow==2.0.0

##### Check the version of the installation

In [4]:
import tensorflow as tf
print(tf.__version__)

2.0.0


Now Let us import out data and get it ready for modelling.

In [8]:
import pandas as pd
import numpy as np
import os

os.chdir('/content/drive/My Drive/GreatLearning Mentoring/Week 17 - Artificial NNs')

cars_data = pd.read_csv('usedcars.csv')
cars_data

year model  price  mileage   color transmission
0    2011   SEL  21992     7413  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [9]:
cars_data.isna().sum()

year            0
model           0
price           0
mileage         0
color           0
transmission    0
dtype: int64

In [10]:
#creating dummy variables for the categorical features
cars_data = pd.get_dummies(cars_data)
cars_data = cars_data.astype('float32') # we will need to convert the dataset to float in order to be able to convert it into tensors later.
cars_data


year    price  ...  transmission_AUTO  transmission_MANUAL
0    2011.0  21992.0  ...                1.0                  0.0
1    2011.0  20995.0  ...                1.0                  0.0
2    2011.0  19995.0  ...                1.0                  0.0
3    2011.0  17809.0  ...                1.0                  0.0
4    2012.0  17500.0  ...                1.0                  0.0
..      ...      ...  ...                ...                  ...
145  2006.0   6200.0  ...                1.0                  0.0
146  2002.0   5995.0  ...                1.0                  0.0
147  2000.0   5980.0  ...                1.0                  0.0
148  2001.0   4899.0  ...                1.0                  0.0
149  2000.0   3800.0  ...                1.0                  0.0

[150 rows x 17 columns]

In [11]:
#getting the features and labels and finally splitting the test and train data.

from sklearn.model_selection import train_test_split
X = cars_data.drop('price', axis = 1)
Y = cars_data['price']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=1)

#let us scale the data as features are on different scales which might be a problem while modelling
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
# MinMaxScalar has been used here. You can go ahead and use the other scalars available and chcek the effect on the results.
#fitting the transform on test and train separately
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[0.75      , 0.27928138, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.58332825, 0.5233474 , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.75      , 0.21721278, 1.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.83332825, 0.20944397, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.33332825, 0.6878496 , 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.83332825, 0.2253431 , 1.        , ..., 0.        , 1.        ,
        0.        ]], dtype=float32)

In [12]:

# let us now convert the data elements into tensors as we need tensors to be fed into different tensorflow based operations
#X-train and X_test were converted to numpy arrays while transformations while the other two need to be transformed into numpy arrays.
X_train=tf.convert_to_tensor(X_train)
y_train=tf.convert_to_tensor(y_train.values)
X_test=tf.convert_to_tensor(X_test)
y_test=tf.convert_to_tensor(y_test.values)

In [28]:
X_train.shape[1]

16

#### Let us try modelling now. We will use a few concepts covered in the practice exercise shared with the course material.

In [29]:
#### Setup variables
input_dim = X_train.shape[1]
output_dim = 1
learning_rate = 0.01

In [30]:
# Let us initialize the weights and bias variables. 
weights = tf.Variable(tf.zeros(shape=(input_dim, output_dim), dtype= tf.float32))
bias = tf.Variable(tf.ones(shape=(output_dim,), dtype= tf.float32))

In [17]:
# Let us now define a function to train the model. We will call the other functions in function definition.
def predict(features):
    return tf.matmul(features, weights) + bias # note that the matmul is matrix multiplication and is needed for calculating predictions

def compute_loss(y_true, predictions):
    return tf.reduce_mean(tf.square(y_true - predictions)) # mean square error

def train(x, y):
    with tf.GradientTape() as tape:
        predictions = predict(x)
        loss = compute_loss(y, predictions)
        dloss_dw, dloss_db = tape.gradient(loss, [weights, bias]  ) #note that we can pass lists as well here. (dw = weights, db = bias)
    weights.assign_sub(learning_rate * dloss_dw)
    bias.assign_sub(learning_rate * dloss_db)
    return loss


#### Let us now, call the train function with 50 epochs

In [18]:
for epoch in range(50):
    loss = train(X_train, y_train)
    print('Epoch %d: Loss = %.1f' % (epoch, float(loss)))


Epoch 0: Loss = 176731120.0
Epoch 1: Loss = 157933824.0
Epoch 2: Loss = 141282496.0
Epoch 3: Loss = 126532168.0
Epoch 4: Loss = 113465608.0
Epoch 5: Loss = 101890464.0
Epoch 6: Loss = 91636368.0
Epoch 7: Loss = 82552456.0
Epoch 8: Loss = 74505024.0
Epoch 9: Loss = 67375672.0
Epoch 10: Loss = 61059540.0
Epoch 11: Loss = 55463724.0
Epoch 12: Loss = 50505948.0
Epoch 13: Loss = 46113352.0
Epoch 14: Loss = 42221360.0
Epoch 15: Loss = 38772792.0
Epoch 16: Loss = 35717000.0
Epoch 17: Loss = 33009130.0
Epoch 18: Loss = 30609446.0
Epoch 19: Loss = 28482742.0
Epoch 20: Loss = 26597858.0
Epoch 21: Loss = 24927154.0
Epoch 22: Loss = 23446196.0
Epoch 23: Loss = 22133294.0
Epoch 24: Loss = 20969272.0
Epoch 25: Loss = 19937130.0
Epoch 26: Loss = 19021806.0
Epoch 27: Loss = 18209964.0
Epoch 28: Loss = 17489794.0
Epoch 29: Loss = 16850832.0
Epoch 30: Loss = 16283805.0
Epoch 31: Loss = 15780510.0
Epoch 32: Loss = 15333666.0
Epoch 33: Loss = 14936839.0
Epoch 34: Loss = 14584323.0
Epoch 35: Loss = 1427106

In [19]:
print('Final Weights after 50 epochs:')
print(weights)
print('###############################################################################')

print('Final Bias after 50 epochs:')
print(bias)
print('###############################################################################')


Final Weights after 50 epochs:
<tf.Variable 'Variable:0' shape=(16, 1) dtype=float32, numpy=
array([[3008.1316  ],
       [1190.5148  ],
       [2035.1709  ],
       [ 605.12933 ],
       [1614.7789  ],
       [ 831.85315 ],
       [ 515.2115  ],
       [  34.478077],
       [ 466.3804  ],
       [ 203.20662 ],
       [ 746.81555 ],
       [ 910.93    ],
       [ 410.437   ],
       [ 135.7667  ],
       [3421.83    ],
       [ 833.2481  ]], dtype=float32)>
###############################################################################
Final Bias after 50 epochs:
<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([4256.079], dtype=float32)>
###############################################################################


#### Let us now test our model on the test data and predict on the test data.

In [21]:
test_predictions = tf.matmul(X_test, weights) + bias
print(compute_loss(y_test, test_predictions))

tf.Tensor(8548196.0, shape=(), dtype=float32)


In [25]:
test_predictions

<tf.Tensor: id=1881, shape=(30, 1), dtype=float32, numpy=
array([[12966.248],
       [12759.732],
       [11598.596],
       [11823.011],
       [12167.282],
       [10588.252],
       [12544.059],
       [13192.689],
       [11679.381],
       [13533.48 ],
       [13303.452],
       [11865.228],
       [12738.202],
       [12878.569],
       [13292.344],
       [10183.004],
       [12652.132],
       [12997.48 ],
       [10452.417],
       [11850.39 ],
       [12616.388],
       [10689.47 ],
       [12982.405],
       [12955.671],
       [12863.805],
       [ 9874.346],
       [11986.701],
       [12172.322],
       [11634.078],
       [11628.225]], dtype=float32)>

In [26]:
y_test

<tf.Tensor: id=3, shape=(30,), dtype=float32, numpy=
array([16000., 12507., 13584., 15999.,  8800., 13995.,  6995., 14499.,
       14999., 10717., 12780., 17495., 11999., 14275., 13383., 14677.,
       12988., 13950., 14995., 14990., 12992., 12995., 13384., 14761.,
        9995., 12500., 14992., 15992., 13663.,  5995.], dtype=float32)>

We learnt creating a very simple linear regression model on cars data and predicted prices. 

Though, we could have done an extensive EDA and further improved the model but we have focused on tensorflow and its operations.

<i>Happy Learning!</i>