# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [11]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [13]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [14]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.55642832 0.50934305 0.86169413 0.76055389 0.98169982]
 [0.82175993 0.57097263 0.0516012  0.91773073 0.52570887]
 [0.01297456 0.12283084 0.12584774 0.6635586  0.25174703]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]

[[ 2.33064777  3.61479345 -0.42907939  1.19027944  2.03811729]
 [-0.59094315 -0.22035002 -0.22903008  0.08294808  0.23633135]
 [ 0.66356053  0.49373551 -0.62546812 -0.80548475 -0.40340269]
 [ 0.795649   -1.17673403 -0.51694774  0.12836068  0.39208588]
 [ 0.17112956 -0.57748871 -0.00537526  1.13656111 -0.27935125]
 [ 0.7886412  -0.74859489 -0.06066173 -0.12201389  0.04839483]
 [ 1.35606581 -0.02113275  0.5062785  -0.44674686 -1.02707449]
 [ 0.37182763  1.08219611 -0.58159943 -0.94508854  1.51095395]
 [ 0.676959   -0.03544465 -1.21023519 -1.10282937 -0.60342395]
 [ 1.35404932  0.2754752  -1.28798252 -1.83565759 -1.12231798]]


In [15]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4713143286046243
1.0154967955760585


In [16]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.012974558061876529
3.614793450673732


In [ ]:
# break here for next video!

In [17]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.73919656 -1.32549307  1.72986394 -0.40712941 -0.79359062  0.10606895
  0.47643997 -0.15828996 -0.92051478 -2.06279081 -0.49179002  0.52921797
 -0.10529827 -1.07315537  0.1057895   1.19682354 -2.23025777  1.25566424
  1.35388225]
0.4764399732886239


In [18]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.79359062  0.10606895  0.47643997 -0.15828996 -0.92051478]


In [19]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.73919656 -0.40712941  0.47643997 -2.06279081 -0.10529827]


In [20]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.55642832 0.50934305 0.86169413 0.76055389 0.98169982]
 [0.82175993 0.57097263 0.0516012  0.91773073 0.52570887]
 [0.01297456 0.12283084 0.12584774 0.6635586  0.25174703]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]
0.0516011974665358
0.0516011974665358


In [21]:
print(rand_mat[0:2,1:3])

[[0.50934305 0.86169413]
 [0.57097263 0.0516012 ]]


In [22]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-1.73919656 -1.32549307  1.72986394 -0.40712941 -0.79359062  0.10606895
  0.47643997 -0.15828996 -0.92051478 -2.06279081 -0.49179002  0.52921797
 -0.10529827 -1.07315537  0.1057895   1.19682354 -2.23025777  1.25566424
  1.35388225]

[-1.73919656 -1.32549307  1.72986394  4.          4.          0.10606895
  0.47643997 -0.15828996 -0.92051478 -2.06279081 -0.49179002  0.52921797
 -0.10529827 -1.07315537  0.1057895   1.19682354 -2.23025777  1.25566424
  1.35388225]

[-1.73919656 -1.32549307  1.72986394  1.          2.          0.10606895
  0.47643997 -0.15828996 -0.92051478 -2.06279081 -0.49179002  0.52921797
 -0.10529827 -1.07315537  0.1057895   1.19682354 -2.23025777  1.25566424
  1.35388225]


In [23]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.55642832 0.50934305 0.86169413 0.76055389 0.98169982]
 [0.82175993 0.57097263 0.0516012  0.91773073 0.52570887]
 [0.01297456 0.12283084 0.12584774 0.6635586  0.25174703]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]

[[0.55642832 0.50934305 0.86169413 0.76055389 0.98169982]
 [0.82175993 0.57097263 0.0516012  0.         0.        ]
 [0.01297456 0.12283084 0.12584774 0.         0.        ]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]


In [24]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.55642832 0.50934305 0.86169413]
 [0.82175993 0.57097263 0.0516012 ]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [25]:
print(rand_mat)

[[3.         3.         3.         0.76055389 0.98169982]
 [3.         3.         3.         0.         0.        ]
 [0.01297456 0.12283084 0.12584774 0.         0.        ]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]


In [26]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.76055389 0.98169982]
 [3.         3.         3.         0.         0.        ]
 [0.01297456 0.12283084 0.12584774 0.         0.        ]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]


In [ ]:
# break here for next video

In [27]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-1.51555732 -0.03641186  0.50795194  0.27991988 -1.19089862  0.38292598
  1.4657155   0.19349848 -1.11242476  0.6668432  -0.14075008 -0.91378995
  0.5651312   0.32223959  0.13764462]
[False False  True  True False  True  True  True False  True False False
  True  True  True]
[0.50795194 0.27991988 0.38292598 1.4657155  0.19349848 0.6668432
 0.5651312  0.32223959 0.13764462]


In [28]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 2.33064777  3.61479345 -0.42907939  1.19027944  2.03811729]
 [-0.59094315 -0.22035002 -0.22903008  0.08294808  0.23633135]
 [ 0.66356053  0.49373551 -0.62546812 -0.80548475 -0.40340269]
 [ 0.795649   -1.17673403 -0.51694774  0.12836068  0.39208588]
 [ 0.17112956 -0.57748871 -0.00537526  1.13656111 -0.27935125]
 [ 0.7886412  -0.74859489 -0.06066173 -0.12201389  0.04839483]
 [ 1.35606581 -0.02113275  0.5062785  -0.44674686 -1.02707449]
 [ 0.37182763  1.08219611 -0.58159943 -0.94508854  1.51095395]
 [ 0.676959   -0.03544465 -1.21023519 -1.10282937 -0.60342395]
 [ 1.35404932  0.2754752  -1.28798252 -1.83565759 -1.12231798]]
[2.33064777 3.61479345 1.19027944 2.03811729 0.08294808 0.23633135
 0.66356053 0.49373551 0.795649   0.12836068 0.39208588 0.17112956
 1.13656111 0.7886412  0.04839483 1.35606581 0.5062785  0.37182763
 1.08219611 1.51095395 0.676959   1.35404932 0.2754752 ]


In [29]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-1.51555732 -0.03641186  0.50795194  0.27991988 -1.19089862  0.38292598
  1.4657155   0.19349848 -1.11242476  0.6668432  -0.14075008 -0.91378995
  0.5651312   0.32223959  0.13764462]

[-1.51555732 -0.03641186 -5.          0.27991988 -1.19089862  0.38292598
 -5.          0.19349848 -1.11242476 -5.         -0.14075008 -0.91378995
 -5.          0.32223959  0.13764462]


In [30]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [31]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [32]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 2.33064777  3.61479345 -0.42907939  1.19027944  2.03811729]
 [-0.59094315 -0.22035002 -0.22903008  0.08294808  0.23633135]
 [ 0.66356053  0.49373551 -0.62546812 -0.80548475 -0.40340269]
 [ 0.795649   -1.17673403 -0.51694774  0.12836068  0.39208588]
 [ 0.17112956 -0.57748871 -0.00537526  1.13656111 -0.27935125]
 [ 0.7886412  -0.74859489 -0.06066173 -0.12201389  0.04839483]
 [ 1.35606581 -0.02113275  0.5062785  -0.44674686 -1.02707449]
 [ 0.37182763  1.08219611 -0.58159943 -0.94508854  1.51095395]
 [ 0.676959   -0.03544465 -1.21023519 -1.10282937 -0.60342395]
 [ 1.35404932  0.2754752  -1.28798252 -1.83565759 -1.12231798]]



In [33]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.76055389 0.98169982]
 [3.         3.         3.         0.         0.        ]
 [0.01297456 0.12283084 0.12584774 0.         0.        ]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]

[[ 2.33064777  3.61479345 -0.42907939  1.19027944  2.03811729]
 [-0.59094315 -0.22035002 -0.22903008  0.08294808  0.23633135]
 [ 0.66356053  0.49373551 -0.62546812 -0.80548475 -0.40340269]
 [ 0.795649   -1.17673403 -0.51694774  0.12836068  0.39208588]
 [ 0.17112956 -0.57748871 -0.00537526  1.13656111 -0.27935125]
 [ 0.7886412  -0.74859489 -0.06066173 -0.12201389  0.04839483]
 [ 1.35606581 -0.02113275  0.5062785  -0.44674686 -1.02707449]
 [ 0.37182763  1.08219611 -0.58159943 -0.94508854  1.51095395]
 [ 0.676959   -0.03544465 -1.21023519 -1.10282937 -0.60342395]
 [ 1.35404932  0.2754752  -1.28798252 -1.83565759 -1.12231798]]
[[3.         3.         3.         0.76055389 0.98169982]
 [3.         3.    

In [34]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.76055389 0.98169982]
 [3.         3.         3.         0.         0.        ]
 [0.01297456 0.12283084 0.12584774 0.         0.        ]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]

[[3.         3.         3.         0.76055389 0.98169982]
 [3.         3.         3.         0.         0.        ]
 [0.01297456 0.12283084 0.12584774 0.         0.        ]
 [0.14665173 0.49127734 0.16030343 0.71507517 0.13655235]
 [0.03129647 0.66053676 0.6435941  0.67981543 0.3833041 ]]
